#!/bin/bash

#be sure to type in source log before typing in this function
log(){
while true
do
#read 3 numbers and print the largest number
echo "Enter [exercise] [weight] [reps]"
read a b c

echo $a $b $c $(date) >> Logs
done
}