#!/bin/bash

#be sure to type in source log before typing in this function

info(){
    #show all the lines in the file Exercises that have the word Leg in it
    clear
    #echo what each function does
    echo "log [exercise]    logs the exercise and the weight and reps"
    echo "find [arg]        grep for the arg in the staged file"
    echo "undo              undo the last log"
    echo "compress          converts prog.log into the staged file"

}


find(){
    #show all the lines in the file Exercises that have the word Leg in it
    clear
    #have a regex search for words that start with the letter A in PROGRESS.log
    grep $1 staged

}

log(){
    #put the line in the file Exercises that has the $1 value in it into a variable
    var=$1
    echo $var
    #echo var without the number infront of it
    echo "Enter [weight] [reps]"
    while true
    do
        #read 3 numbers and print the largest number
        read b c
        #if b or c is not a number then break
        if ! [[ $b =~ ^[0-9]+$ ]] || ! [[ $c =~ ^[0-9]+$ ]]
            then
            break
        fi
        #echo the line without any numbers in it 
        echo $1, $b, $c, $(date '+%m-%d-%Y') >> prog.log
    done
}

undo(){
    #remove the last line of the file
    sed -i '$d' prog.log
}


compress(){
    #give test.py executable permissions
    chmod +x test.py
    #run test.py
    ./test.py
}